Repository teamcubation/byma-financial-report, pull requests merged in 2024-10, with the labels that each got.

#1 Se armo el scaffolding inicial del proyecto
  .gitattributes
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/teamcubation/reportservice/ReportserviceApplication.java
  src/main/java/com/teamcubation/reportservice/application/port/in/.gitkeep
  src/main/java/com/teamcubation/reportservice/application/port/out/.gitkeep
  src/main/java/com/teamcubation/reportservice/application/service/.gitkeep
  src/main/java/com/teamcubation/reportservice/domain/custom-exceptions/.gitkeep
  src/main/java/com/teamcubation/reportservice/domain/model/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/request/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/response/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/mapper/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/adapter/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/entity/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/mapper/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/repository/.gitkeep
  src/main/resources/application.properties
  src/test/java/com/teamcubation/reportservice/ReportserviceApplicationTests.java
Labels: Review effort [1-5]: 4

#3 Implementacion basica del security config con http basic
  pom.xml
  src/main/java/com/teamcubation/reportservice/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: Review effort [1-5]: 2

#6 Feature/entidad usuario
  src/main/java/com/teamcubation/reportservice/domain/model/report/CategoryReport.java
  src/main/java/com/teamcubation/reportservice/domain/model/report/FilterReport.java
  src/main/java/com/teamcubation/reportservice/domain/model/report/Report.java
  src/main/java/com/teamcubation/reportservice/domain/model/user/User.java
  src/main/java/com/teamcubation/reportservice/domain/model/user/UserRole.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/request/UserRequest.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/response/UserResponse.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/mapper/UserMapper.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/entity/UserEntity.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/mapper/UserPersistenceMapper.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/repository/UserRepository.java
Labels: Review effort [1-5]: 4

#5 Agregado el Global Exception Handler
  src/main/java/com/teamcubation/reportservice/domain/MockCustomException.java
  src/main/java/com/teamcubation/reportservice/exceptionHandler/ErrorMessage.java
  src/main/java/com/teamcubation/reportservice/exceptionHandler/GlobalExceptionHandler.java
Labels: Review effort [1-5]: 3

#4 Agregado el userdetails y el userdetailsService
  README.md
  Report Service API.postman_collection.json
  src/main/java/com/teamcubation/reportservice/application/port/out/MockUserOutPort.java
  src/main/java/com/teamcubation/reportservice/application/service/.gitkeep
  src/main/java/com/teamcubation/reportservice/application/service/UserDetailsServiceImpl.java
  src/main/java/com/teamcubation/reportservice/config/SecurityConfig.java
  src/main/java/com/teamcubation/reportservice/domain/model/user/UserAuthenticated.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/MockController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/entity/user/MockUserEntity.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/repository/user/MockUserRepository.java
Labels: Review effort [1-5]: 3

#12 controler implementado
  src/main/java/com/teamcubation/reportservice/application/service/UserService.java
  src/main/java/com/teamcubation/reportservice/exceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/UserController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/request/UserRequest.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/request/UserRequest.java~
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/response/UserResponse.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/mapper/UserMapper.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/adapter/user/UserOutAdapter.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/mapper/UserPersistenceMapper.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/repository/user/UserRepository.java
Labels: Review effort [1-5]: 4

#9 Feature/creacion de entidad y mapper
  src/main/java/com/teamcubation/reportservice/domain/model/report/CategoryReport.java
  src/main/java/com/teamcubation/reportservice/domain/model/report/FilterReport.java
  src/main/java/com/teamcubation/reportservice/domain/model/report/Report.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/entity/ReportEntity.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/mapper/ReportPersistenceMapper.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/repository/ReportOutAdapter.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/repository/ReportRepository.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/util/validation/PersistenceValidation.java
Labels: Review effort [1-5]: 3

#11 Conectar con microservicios Bond y Stock
  src/main/java/com/teamcubation/reportservice/application/port/out/ConnectionOutPort.java
  src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
  src/main/java/com/teamcubation/reportservice/config/ConfigService.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/ReportController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/ConnectionBond.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/ConnectionInstrument.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/ConnectionStock.java
Labels: Review effort [1-5]: 4

#13 Feature/integracion y roles
  src/main/java/com/teamcubation/reportservice/application/port/in/AuthInPort.java
  src/main/java/com/teamcubation/reportservice/application/port/out/AuthOutPort.java
  src/main/java/com/teamcubation/reportservice/application/service/AuthService.java
  src/main/java/com/teamcubation/reportservice/application/service/AuthService.java~
  src/main/java/com/teamcubation/reportservice/application/service/UserDetailsServiceImpl.java
  src/main/java/com/teamcubation/reportservice/config/ApplicationConfig.java
  src/main/java/com/teamcubation/reportservice/config/SecurityConfig.java
  src/main/java/com/teamcubation/reportservice/domain/model/user/UserAuthenticated.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/AuthController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/request/LoginRequestDTO.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/request/RegisterRequestDTO.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/response/TokenResponseDTO.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/mapper/AuthMapper.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/adapter/auth/AuthOutAdapter.java
  src/main/resources/application.properties
Labels: Review effort [1-5]: 4

#14 generador de csv y pdf con su descarga
  out/production/byma-financial-report/com/teamcubation/reportservice/application/port/out/.gitkeep
  out/production/byma-financial-report/com/teamcubation/reportservice/application/service/.gitkeep
  out/production/byma-financial-report/com/teamcubation/reportservice/domain/custom-exceptions/.gitkeep
  out/production/byma-financial-report/com/teamcubation/reportservice/domain/model/.gitkeep
  out/production/byma-financial-report/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/.gitkeep
  out/production/byma-financial-report/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/adapter/.gitkeep
  out/production/byma-financial-report/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/entity/.gitkeep
  out/production/byma-financial-report/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/repository/.gitkeep
  pom.xml
  src/main/java/com/teamcubation/reportservice/application/port/in/ReportInPort.java
  src/main/java/com/teamcubation/reportservice/application/port/out/ConnectionOutPort.java
  src/main/java/com/teamcubation/reportservice/application/service/GeneratorCsv.java
  src/main/java/com/teamcubation/reportservice/application/service/GeneratorPdf.java
  src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
  src/main/java/com/teamcubation/reportservice/domain/model/report/Report.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/ReportController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/ConnectionBond.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/ConnectionInstrument.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/ConnectionStock.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/dto/BonoDto.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/dto/StockDto.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/entity/ReportEntity.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/mapper/entityToDomain.java
Labels: Review effort [1-5]: 4

#17 Feature/conectar service repository
  src/main/java/com/teamcubation/reportservice/ReportserviceApplication.java
  src/main/java/com/teamcubation/reportservice/application/port/in/ReportInPort.java
  src/main/java/com/teamcubation/reportservice/application/port/out/ReportOutPort.java
  src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
  src/main/java/com/teamcubation/reportservice/application/service/generatorfile/GeneratorCsv.java
  src/main/java/com/teamcubation/reportservice/application/service/generatorfile/GeneratorPdf.java
  src/main/java/com/teamcubation/reportservice/config/ConfigService.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/ReportController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/response/ReportResponse.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/ConnectionBond.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/ConnectionStock.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/entity/ReportEntity.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/repository/ReportOutAdapter.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/repository/ReportRepository.java
  src/main/resources/application.properties
Labels: Review effort [1-5]: 4

#18 Cache
  pom.xml
  src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
  src/main/java/com/teamcubation/reportservice/application/service/UserService.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/cacheCongif/CacheConfig.java
Labels: Review effort [1-5]: 4

#19 Agregamos ApiConsumer para sacar creación de RestTemplate del Config
  src/main/java/com/teamcubation/reportservice/config/ConfigService.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/ApiConsumer.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/ConnectionBond.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/externalapi/ConnectionStock.java
Labels: Review effort [1-5]: 2

#21 subo documentacion con el swagger ya implementado
  MS REPORT.postman_collection.json
  README.md
  Report Service API.postman_collection.json
  pom.xml
  src/main/java/com/teamcubation/reportservice/application/port/in/UserInPort.java
  src/main/java/com/teamcubation/reportservice/application/port/out/UserOutPort.java
  src/main/java/com/teamcubation/reportservice/application/service/UserService.java
  src/main/java/com/teamcubation/reportservice/config/SecurityConfig.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/.gitkeep
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/ApiAuth.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/ApiMock.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/ApiReport.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/ApiUser.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/SwaggerConfig.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/AuthController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/MockController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/ReportController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/UserController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/adapter/user/UserOutAdapter.java
Labels: Review effort [1-5]: 4

#26 Se agrega funcionalidad para recuperar los reportes por userEmail, ta…
  src/main/java/com/teamcubation/reportservice/application/port/in/ReportInPort.java
  src/main/java/com/teamcubation/reportservice/application/port/out/ReportOutPort.java
  src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
  src/main/java/com/teamcubation/reportservice/domain/model/report/Report.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/ReportController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/adapter/report/ReportOutAdapter.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/entity/ReportEntity.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/mapper/ReportPersistenceMapper.java
  src/main/resources/application.properties
Labels: Review effort [1-5]: 3

#22 se agrega testing del service y excepciones personalizadas
  src/main/java/com/teamcubation/reportservice/application/service/ReportService.java
  src/main/java/com/teamcubation/reportservice/domain/custom-exceptions/.gitkeep
  src/main/java/com/teamcubation/reportservice/domain/customexceptions/report/InvalidInstrumentException.java
  src/main/java/com/teamcubation/reportservice/domain/customexceptions/report/InvalidTypeFyleException.java
  src/test/java/com/teamcubation/reportservice/controllerReport/ControllerTest.java
  src/test/java/com/teamcubation/reportservice/serviceReport/ServiceTest.java
Labels: Review effort [1-5]: 4

#23 actualizado el http filter chain e incorporado endpoint de actualizac…
  src/main/java/com/teamcubation/reportservice/application/port/in/AuthInPort.java
  src/main/java/com/teamcubation/reportservice/application/port/in/UserInPort.java
  src/main/java/com/teamcubation/reportservice/application/port/out/AuthOutPort.java
  src/main/java/com/teamcubation/reportservice/application/port/out/UserOutPort.java
  src/main/java/com/teamcubation/reportservice/application/service/AuthService.java
  src/main/java/com/teamcubation/reportservice/application/service/UserService.java
  src/main/java/com/teamcubation/reportservice/application/service/exception/InvalidUserModel.java
  src/main/java/com/teamcubation/reportservice/application/service/exception/UserDuplicateException.java
  src/main/java/com/teamcubation/reportservice/application/service/exception/UserNotFoundException.java
  src/main/java/com/teamcubation/reportservice/config/SecurityConfig.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/ApiAuth.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/ApiUser.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/AuthController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/MockController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/ReportController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/controller/impl/UserController.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/request/UserRequest.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/request/UserUpdateRequestDTO.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/mapper/UserMapper.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/validation/ControllerValidator.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/adapter/auth/AuthOutAdapter.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/adapter/user/UserOutAdapter.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/mapper/UserPersistenceMapper.java
  src/test/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/adapter/user/UserOutAdapterTest.java
Labels: Review effort [1-5]: 4

#27 Feature/roles persistance
  src/main/java/com/teamcubation/reportservice/application/service/AuthService.java
  src/main/java/com/teamcubation/reportservice/application/service/Jwt/JwtService.java
  src/main/java/com/teamcubation/reportservice/application/service/UserDetailsServiceImpl.java
  src/main/java/com/teamcubation/reportservice/application/service/UserService.java
  src/main/java/com/teamcubation/reportservice/domain/model/user/Rol/Role.java
  src/main/java/com/teamcubation/reportservice/domain/model/user/User.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/request/UserRequest.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/dto/response/UserResponse.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/mapper/AuthMapper.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/in/web/mapper/UserMapper.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/entity/user/UserEntity.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/entity/user/role/RoleEntity.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/mapper/UserPersistenceMapper.java
  src/main/java/com/teamcubation/reportservice/infrastructure/adapter/out/persistance/repository/user/RoleRepository.java
Labels: Review effort [1-5]: 4

#30 Se agregaron las custom exceptions al global exception handler
  src/main/java/com/teamcubation/reportservice/domain/MockCustomException.java
  src/main/java/com/teamcubation/reportservice/exceptionHandler/GlobalExceptionHandler.java
Labels: Review effort [1-5]: 2
